name: Container-Retention
on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"  # every hour

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete all untagged images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: tma84
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "*"
          tag-selection: untagged  # target any image that has a tag starting with the word test or dev
          cut-off: 1h
          dry-run: true

